### ISSUE TITLE
java.io.NotSerializableException

### ISSUE THREAD

**Issue by goldmar** [scalameter/scalameter#21]
Hi,

I'm trying to use ScalaMeter. When I use LocalExecutor everything's working fine but with SeparateJvmsExecutor I'm getting the following error:

java.io.NotSerializableException: performances.CEPPerformanceTest

Any ideas how to fix this?

Attached is the full stack trace.

Regards,
Mark

```
java.io.NotSerializableException: performances.CEPPerformanceTest
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1541)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1506)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1429)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1541)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1506)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1429)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1541)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1506)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1429)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1541)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1506)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1429)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1541)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1506)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1429)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
    at org.scalameter.execution.package$JvmRunner.serializeInput(package.scala:35)
    at org.scalameter.execution.package$JvmRunner.run(package.scala:26)
    at org.scalameter.execution.SeparateJvmsExecutor.sample$1(SeparateJvmsExecutor.scala:39)
    at org.scalameter.execution.SeparateJvmsExecutor.org$scalameter$execution$SeparateJvmsExecutor$$sampleReport$1(SeparateJvmsExecutor.scala:73)
    at org.scalameter.execution.SeparateJvmsExecutor$$anonfun$3.apply(SeparateJvmsExecutor.scala:87)
    at org.scalameter.execution.SeparateJvmsExecutor$$anonfun$3.apply(SeparateJvmsExecutor.scala:85)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalameter.execution.SeparateJvmsExecutor.runSetup(SeparateJvmsExecutor.scala:85)
    at org.scalameter.Executor$$anonfun$run$1.apply(Executor.scala:16)
    at org.scalameter.Executor$$anonfun$run$1.apply(Executor.scala:14)
    at org.scalameter.utils.Tree$$anonfun$1.apply(Tree.scala:17)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalameter.utils.Tree.map(Tree.scala:17)
    at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
    at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalameter.utils.Tree.map(Tree.scala:18)
    at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
    at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalameter.utils.Tree.map(Tree.scala:18)
    at org.scalameter.Executor$class.run(Executor.scala:14)
    at org.scalameter.execution.SeparateJvmsExecutor.run(SeparateJvmsExecutor.scala:18)
    at org.scalameter.PerformanceTest$Initialization$class.executeTests(PerformanceTest.scala:44)
    at org.scalameter.PerformanceTest.executeTests(PerformanceTest.scala:10)
    at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaMeterFramework.scala:65)
    at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaMeterFramework.scala:60)
    at org.scalameter.package$MonadicDynVar$$anon$3$$anonfun$foreach$1.apply(package.scala:20)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.scalameter.package$MonadicDynVar$$anon$3.foreach(package.scala:20)
    at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(ScalaMeterFramework.scala:60)
    at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(ScalaMeterFramework.scala:59)
    at org.scalameter.package$MonadicDynVar$$anon$3$$anonfun$foreach$1.apply(package.scala:20)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.scalameter.package$MonadicDynVar$$anon$3.foreach(package.scala:20)
    at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1.apply(ScalaMeterFramework.scala:59)
    at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1.apply(ScalaMeterFramework.scala:58)
    at org.scalameter.package$MonadicDynVar$$anon$3$$anonfun$foreach$1.apply(package.scala:20)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.scalameter.package$MonadicDynVar$$anon$3.foreach(package.scala:20)
    at org.scalameter.ScalaMeterFramework$$anon$1.run(ScalaMeterFramework.scala:58)
    at sbt.TestRunner.delegateRun(TestFramework.scala:58)
    at sbt.TestRunner.run(TestFramework.scala:51)
    at sbt.TestRunner.runTest$1(TestFramework.scala:71)
    at sbt.TestRunner.run(TestFramework.scala:80)
    at sbt.TestFramework$$anonfun$9$$anonfun$apply$9$$anonfun$10$$anonfun$apply$10.apply(TestFramework.scala:188)
    at sbt.TestFramework$$anonfun$9$$anonfun$apply$9$$anonfun$10$$anonfun$apply$10.apply(TestFramework.scala:188)
    at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:200)
    at sbt.TestFramework$$anonfun$9$$anonfun$apply$9$$anonfun$10.apply(TestFramework.scala:188)
    at sbt.TestFramework$$anonfun$9$$anonfun$apply$9$$anonfun$10.apply(TestFramework.scala:188)
    at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:119)
    at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:119)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
[error] Could not run test performances.CEPPerformanceTest: java.io.NotSerializableException: performances.CEPPerformanceTest
```

**Comment by l15k4** [comment]
I have this argument serialization problem too : 
```
java.lang.RuntimeException: failed to parse args: `false' expected but end of source found
	at scala.sys.package$.error(package.scala:27)
	at org.scalameter.Main$Configuration$.fromCommandLineArgs(Main.scala:80)
	at org.scalameter.ScalaMeterFramework$$anon$1.run(ScalaMeterFramework.scala:58)
	at sbt.RunnerWrapper$1.runRunner2(FrameworkWrapper.java:223)
	at sbt.RunnerWrapper$1.execute(FrameworkWrapper.java:236)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
```
lazy val `etl-benchmarks` = (project in file("src/benchmarks"))
  .dependsOn(
    `etl-backup` % "compile->compile;test->test",
    `etl-base` % "compile->compile;test->test",
    `etl-overlap` % "compile->compile;test->test",
    `etl-druid` % "compile->compile;test->test"
  ).settings(
    name := "etl-benchmarks",
    testFrameworks += new TestFramework("org.scalameter.ScalaMeterFramework"),
    libraryDependencies += "com.storm-enroute" %% "scalameter" % "0.8.2"
)
```
 
```
object FooBenchmark extends OnlineRegressionReport
```

Now this error happens even with this empty `FooBenchmark` ... It is somehow caused  by depending on those 4 sbt projects ...
