### ISSUE TITLE
Errors when using SeparateJvmsExecutor

### ISSUE THREAD

**Issue by ColOfAbRiX** [scalameter/scalameter#231]
I'm using Scalameter in a personal project with these version:

* Scala 2.13.2
* Scalameter 0.20.
* SBT 1.4.6

When I use the executor `SeparateJvmsExecutor` I ran into a series of problem. The first thing that happens is this exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
        at org.scalameter.execution.SeparateJvmFailure.<init>(SeparateJvmFailure.scala:3)
        at org.scalameter.execution.Main$.saveFailure(Main.scala:50)
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2960)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1540)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at org.scalameter.execution.JvmRunner.readOutput(JvmRunner.scala:74)
```
Digging into the issue I found that the JvmRunner includes in the classpath also SBT jars and that creates conflicts.

**Comment by ColOfAbRiX** [comment]
See https://github.com/ColOfAbRiX/scalameter/commit/08cb9174803a7beb4f3ecd8102b6de7c0f0e78b6 for a possible solution. I'm just removing any classpath that refers to SBT

**Comment by ColOfAbRiX** [comment]
After that issue I started receving another exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
        at org.scalameter.execution.SeparateJvmFailure.<init>(SeparateJvmFailure.scala:3)
        at org.scalameter.execution.Main$.saveFailure(Main.scala:50)
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2960)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1540)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at org.scalameter.execution.JvmRunner.readOutput(JvmRunner.scala:74)
        at org.scalameter.execution.JvmRunner.run(JvmRunner.scala:22)
```
and with a bit of digging it's a known issue with Scala serialization as discussed in this thread https://github.com/scala/bug/issues/9237

I added a new object to deserialize the data in this commit https://github.com/ColOfAbRiX/scalameter/commit/99d54aec82117cde0f836748544935b734e5a94a

**Comment by ColOfAbRiX** [comment]
Unfortunately that's no the end of it.

While the `LoggingReporter()` reporter works, it seems that using
```
 Reporter.Composite(
   new RegressionReporter(tester, historian),
   HtmlReporter(embedDsv = true),
)
```
creates more problems with different exceptions.

**Comment by froth** [comment]
Same here :(

**Comment by MercurieVV** [comment]
My workaround for this is following.
I already created sbt config Benchmark for this.
In my module I specify classloader for this config `inConfig(Benchmark)(classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat)`
Maybe other strategies will work too. I didnt try to get deeper and check
